const DATA = [
  {
    _id: 1,
    name: 'Palm Wood',
    price: 1200,
    location: 'New York, USA',
    address: '2699 Green Valley',
    popular: true,
    beds: 3,
    bathrooms: 2,
    area: '5x7',
    image: 'https://via.placeholder.com/300x160',
  },
  {
    _id: 2,
    name: 'Palm Harbor',
    price: 2500,
    location: 'Texas, USA',
    address: '26 New Town Road',
    popular: true,
    beds: 4,
    bathrooms: 4,
    area: '7x8',
    image: 'https://via.placeholder.com/300x160',
  },
  {
    _id: 3,
    name: 'Faulkner Ave',
    price: 2000,
    location: 'Texas, USA',
    address: '17 Harbor Road',
    popular: false,
    beds: 2,
    bathrooms: 2,
    area: '5x6',
    image: 'https://via.placeholder.com/300x160',
  },
  {
    _id: 4,
    name: 'Beverly Springfield',
    price: 1000,
    location: 'Ohio, USA',
    address: '51 Eva Street',
    popular: false,
    beds: 3,
    bathrooms: 2,
    area: '5x7',
    image: 'https://via.placeholder.com/300x160',
  },
  {
    _id: 5,
    name: 'Wood Oak',
    price: 3500,
    location: 'New York, USA',
    address: '27/28 Wook Oak Road',
    popular: true,
    beds: 4,
    bathrooms: 4,
    area: '9x10',
    image: 'https://via.placeholder.com/300x160',
  },
  {
    _id: 6,
    name: 'Green Wood',
    price: 1800,
    location: 'California, USA',
    address: '2687 Green Wood City',
    popular: false,
    beds: 1,
    bathrooms: 1,
    area: '5x7',
    image: 'https://via.placeholder.com/300x160',
  },
  {
    _id: 7,
    name: 'Harbor Heights',
    price: 2500,
    location: 'Ohio, USA',
    address: '93 HNH Street',
    popular: true,
    beds: 3,
    bathrooms: 2,
    area: '6x7',
    image: 'https://via.placeholder.com/300x160',
  },
  {
    _id: 8,
    name: 'Arpwood Capital',
    price: 700,
    location: 'Texas, USA',
    address: '33 Arc Street',
    popular: true,
    beds: 2,
    bathrooms: 2,
    area: '4x5',
    image: 'https://via.placeholder.com/300x160',
  },
  {
    _id: 9,
    name: 'Palm Oak',
    price: 4200,
    location: 'New York, USA',
    address: '69 Green Valley',
    popular: false,
    beds: 4,
    bathrooms: 2,
    area: '6x7',
    image: 'https://via.placeholder.com/300x160',
  },
  {
    _id: 10,
    name: 'Hudson Heights',
    price: 2100,
    location: 'California, USA',
    address: '77 Hudson Lane',
    popular: false,
    beds: 4,
    bathrooms: 2,
    area: '5x7',
    image: 'https://via.placeholder.com/300x160',
  },
];

export default DATA;